# Generated by Django 4.2.30 on 2026-05-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idosos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico_familiar', models.TextField(blank=True, verbose_name='Histórico Familiar')),
                ('historico_pessoal', models.TextField(blank=True, verbose_name='Histórico Pessoal')),
                ('cirurgias_anteriores', models.TextField(blank=True)),
                ('vacinas', models.TextField(blank=True, verbose_name='Histórico de Vacinas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('idoso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='idosos.idoso')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('tipo', models.CharField(choices=[('rotina', 'Consulta de Rotina'), ('urgencia', 'Urgência'), ('retorno', 'Retorno'), ('especialidade', 'Especialidade'), ('preventiva', 'Preventiva')], default='rotina', max_length=15)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('falta', 'Falta')], default='agendada', max_length=10)),
                ('queixa_principal', models.TextField(blank=True, verbose_name='Queixa Principal')),
                ('anamnese', models.TextField(blank=True, verbose_name='Anamnese')),
                ('exame_fisico', models.TextField(blank=True, verbose_name='Exame Físico')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('prescricao', models.TextField(blank=True, verbose_name='Prescrição / Conduta')),
                ('retorno_em', models.DateField(blank=True, null=True, verbose_name='Retorno Previsto')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='idosos.idoso')),
                ('medico', models.ForeignKey(limit_choices_to={'perfil': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data_hora'],
            },
        ),
    ]
