# Generated by Django 4.2.30 on 2026-05-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_profissional', models.CharField(blank=True, max_length=30, verbose_name='Registro Profissional (CRM/CREFITO etc.)')),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('vinculo', models.CharField(choices=[('clt', 'CLT'), ('pj', 'Pessoa Jurídica'), ('voluntario', 'Voluntário'), ('estagio', 'Estágio')], default='clt', max_length=12)),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carga_horaria', models.IntegerField(default=44, verbose_name='Carga Horária Semanal (h)')),
                ('turno', models.CharField(blank=True, max_length=20, verbose_name='Turno de Trabalho')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
