# Generated by Django 4.2.30 on 2026-05-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idosos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoFisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('duracao_minutos', models.IntegerField(default=45, verbose_name='Duração (min)')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('falta', 'Falta do Idoso')], default='agendada', max_length=10)),
                ('objetivo', models.CharField(blank=True, max_length=200, verbose_name='Objetivo da Sessão')),
                ('procedimentos', models.TextField(blank=True, verbose_name='Procedimentos Realizados')),
                ('evolucao', models.TextField(blank=True, verbose_name='Evolução do Paciente')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fisioterapeuta', models.ForeignKey(limit_choices_to={'perfil': 'fisioterapeuta'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_fisio', to='idosos.idoso')),
            ],
            options={
                'verbose_name': 'Sessão de Fisioterapia',
                'verbose_name_plural': 'Sessões de Fisioterapia',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PlanoReabilitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do Plano')),
                ('objetivo_geral', models.TextField(verbose_name='Objetivo Geral')),
                ('exercicios', models.TextField(verbose_name='Exercícios Prescritos')),
                ('frequencia_semanal', models.IntegerField(default=3, verbose_name='Sessões por Semana')),
                ('data_inicio', models.DateField()),
                ('data_previsao_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fisioterapeuta', models.ForeignKey(limit_choices_to={'perfil': 'fisioterapeuta'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_reab', to='idosos.idoso')),
            ],
            options={
                'verbose_name': 'Plano de Reabilitação',
                'verbose_name_plural': 'Planos de Reabilitação',
            },
        ),
    ]
