# Generated by Django 4.2.30 on 2026-05-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idosos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Medicamento')),
                ('principio_ativo', models.CharField(blank=True, max_length=150)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('forma', models.CharField(blank=True, help_text='Ex: comprimido, xarope, injeção', max_length=50, verbose_name='Forma Farmacêutica')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.IntegerField(default=10, verbose_name='Estoque Mínimo')),
                ('unidade', models.CharField(default='unidade', max_length=20, verbose_name='Unidade de Medida')),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PrescricaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=50, verbose_name='Dose')),
                ('frequencia', models.CharField(choices=[('1x_dia', '1x ao dia'), ('2x_dia', '2x ao dia'), ('3x_dia', '3x ao dia'), ('4x_dia', '4x ao dia'), ('cada_6h', 'A cada 6 horas'), ('cada_8h', 'A cada 8 horas'), ('cada_12h', 'A cada 12 horas'), ('sob_demanda', 'Sob demanda'), ('semanal', 'Semanal'), ('customizado', 'Customizado')], max_length=15)),
                ('horarios', models.CharField(blank=True, help_text='Ex: 08:00, 12:00, 18:00', max_length=200, verbose_name='Horários')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim (deixe em branco para uso contínuo)')),
                ('via_administracao', models.CharField(blank=True, help_text='Ex: oral, subcutânea, intravenosa', max_length=50, verbose_name='Via de Administração')),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='idosos.idoso')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='medicamentos.medicamento')),
                ('prescrito_por', models.ForeignKey(limit_choices_to={'perfil': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescricoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescrição',
                'verbose_name_plural': 'Prescrições',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAdministracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('status', models.CharField(choices=[('administrado', 'Administrado'), ('recusado', 'Recusado pelo idoso'), ('adiado', 'Adiado'), ('omitido', 'Omitido')], default='administrado', max_length=15)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('administrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administracoes', to=settings.AUTH_USER_MODEL)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='medicamentos.prescricaomedicamento')),
            ],
            options={
                'verbose_name': 'Registro de Administração',
                'verbose_name_plural': 'Registros de Administração',
                'ordering': ['-data_hora'],
            },
        ),
    ]
