# Generated by Django 4.2.30 on 2026-05-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='idosos/')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('internado', 'Internado'), ('falecido', 'Falecido')], default='ativo', max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('condicoes_medicas', models.TextField(blank=True, verbose_name='Condições Médicas')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('numero_quarto', models.CharField(blank=True, max_length=10, verbose_name='Quarto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Idoso',
                'verbose_name_plural': 'Idosos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FamiliarVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('contato_principal', models.BooleanField(default=False, verbose_name='Contato Principal')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('familiar', models.ForeignKey(limit_choices_to={'perfil': 'familiar'}, on_delete=django.db.models.deletion.CASCADE, related_name='idosos_vinculados', to=settings.AUTH_USER_MODEL)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='idosos.idoso')),
            ],
            options={
                'verbose_name': 'Vínculo Familiar',
                'verbose_name_plural': 'Vínculos Familiares',
                'unique_together': {('familiar', 'idoso')},
            },
        ),
    ]
