# Generated by Django 4.2.30 on 2026-05-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idosos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('higiene', 'Higienização'), ('alimentacao', 'Alimentação'), ('medicamento', 'Medicamento'), ('fisioterapia', 'Fisioterapia'), ('lazer', 'Atividade de Lazer'), ('outro', 'Outro')], max_length=15)),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('dias_semana', models.CharField(help_text='Ex: seg,ter,qua,qui,sex ou todos', max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horário de Atividade',
                'verbose_name_plural': 'Horários de Atividades',
                'ordering': ['horario'],
            },
        ),
        migrations.CreateModel(
            name='RotinaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('turno', models.CharField(choices=[('manha', 'Manhã (06h–12h)'), ('tarde', 'Tarde (12h–18h)'), ('noite', 'Noite (18h–06h)')], max_length=6)),
                ('banho_realizado', models.BooleanField(default=False, verbose_name='Banho Realizado')),
                ('higiene_oral', models.BooleanField(default=False, verbose_name='Higiene Oral')),
                ('troca_roupa', models.BooleanField(default=False, verbose_name='Troca de Roupa')),
                ('curativo', models.BooleanField(default=False, verbose_name='Curativo Realizado')),
                ('obs_higiene', models.TextField(blank=True, verbose_name='Obs. Higienização')),
                ('refeicoes_realizadas', models.CharField(blank=True, max_length=200, verbose_name='Refeições Realizadas')),
                ('aceitacao_alimentar', models.CharField(blank=True, choices=[('total', 'Total'), ('parcial', 'Parcial'), ('recusou', 'Recusou')], max_length=10, verbose_name='Aceitação Alimentar')),
                ('obs_alimentacao', models.TextField(blank=True, verbose_name='Obs. Alimentação')),
                ('observacoes_gerais', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='idosos.idoso')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotinas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rotina Diária',
                'verbose_name_plural': 'Rotinas Diárias',
                'ordering': ['-data', 'turno'],
                'unique_together': {('idoso', 'data', 'turno')},
            },
        ),
    ]
