# Generated by Django 4.2.30 on 2026-09-12 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idosos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dias_semana', models.CharField(help_text='Códigos separados por vírgula, ex: seg,qua,sex', max_length=30, verbose_name='Dias da Semana')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim (deixe em branco para sem prazo)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_atividades', to='idosos.idoso')),
                ('prescrito_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_prescritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist de Atividade',
                'verbose_name_plural': 'Checklists de Atividades',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Atividade')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='atividades.checklistatividade')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Itens de Checklist',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('realizado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='atividades.itemchecklist')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Item de Checklist',
                'verbose_name_plural': 'Registros de Itens de Checklist',
                'ordering': ['-data'],
                'unique_together': {('item', 'data')},
            },
        ),
    ]
